apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinpoint-message-converter
spec:
  selector:
    matchLabels:
      app: pinpoint-message-converter
  replicas: 10
  template:
    metadata:
      labels:
        app: pinpoint-message-converter
    spec:
      containers:
      - name: pinpoint-message-converter
        image: pinpoint-message-converter:1.4.1
        imagePullPolicy: Never
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "29.120.136.13:19092,29.120.136.14:19092,29.120.136.15:19092"
        - name: KAFKA_TOPICS
          value: "SpanTopic"
        - name: KAFKA_GROUP_ID
          value: "pinpoint-message-convertor"
        - name: KAFKA_CONSUMER_OFFSET_RESET
          value: "latest"

        # Redis environment variables
        - name: REDIS_HOST
          value: "redis.middleware.svc"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: "viFRKZiZk0%PmXnyF"
        - name: REDIS_DB
          value: "0"

        # GRPC environment variables
        - name: GRPC_SERVER_ADDRESS
          value: "datakit-service.datakit.svc:9991"
