# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/CustomMetric.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15v1/CustomMetric.proto\x12\x02v1\"l\n\x14PCustomMetricMessage\x12\x11\n\ttimestamp\x18\x01 \x03(\x03\x12\x17\n\x0f\x63ollectInterval\x18\x02 \x03(\x03\x12(\n\rcustomMetrics\x18\x03 \x03(\x0b\x32\x11.v1.PCustomMetric\"\x8c\x02\n\rPCustomMetric\x12-\n\x0eintCountMetric\x18\x01 \x01(\x0b\x32\x13.v1.PIntCountMetricH\x00\x12/\n\x0flongCountMetric\x18\x02 \x01(\x0b\x32\x14.v1.PLongCountMetricH\x00\x12-\n\x0eintGaugeMetric\x18\x03 \x01(\x0b\x32\x13.v1.PIntGaugeMetricH\x00\x12/\n\x0flongGaugeMetric\x18\x04 \x01(\x0b\x32\x14.v1.PLongGaugeMetricH\x00\x12\x32\n\x11\x64oubleGaugeMetric\x18\x05 \x01(\x0b\x32\x15.v1.PDouleGaugeMetricH\x00\x42\x07\n\x05\x66ield\">\n\x0fPIntCountMetric\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1d\n\x06values\x18\x02 \x03(\x0b\x32\r.v1.PIntValue\"@\n\x10PLongCountMetric\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1e\n\x06values\x18\x02 \x03(\x0b\x32\x0e.v1.PLongValue\">\n\x0fPIntGaugeMetric\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1d\n\x06values\x18\x02 \x03(\x0b\x32\r.v1.PIntValue\"@\n\x10PLongGaugeMetric\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1e\n\x06values\x18\x02 \x03(\x0b\x32\x0e.v1.PLongValue\"C\n\x11PDouleGaugeMetric\x12\x0c\n\x04name\x18\x01 \x01(\t\x12 \n\x06values\x18\x02 \x03(\x0b\x32\x10.v1.PDoubleValue\",\n\tPIntValue\x12\r\n\x05value\x18\x01 \x01(\x05\x12\x10\n\x08isNotSet\x18\x02 \x01(\x08\"-\n\nPLongValue\x12\r\n\x05value\x18\x01 \x01(\x03\x12\x10\n\x08isNotSet\x18\x02 \x01(\x08\"/\n\x0cPDoubleValue\x12\r\n\x05value\x18\x01 \x01(\x01\x12\x10\n\x08isNotSet\x18\x02 \x01(\x08\x42\x8a\x01\n!com.navercorp.pinpoint.grpc.traceB\x11\x43ustomMetricProtoP\x01ZPgitlab.jiagouyun.com/cloudcare-tools/datakit/plugins/inputs/pinpoint/compiled/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.CustomMetric_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n!com.navercorp.pinpoint.grpc.traceB\021CustomMetricProtoP\001ZPgitlab.jiagouyun.com/cloudcare-tools/datakit/plugins/inputs/pinpoint/compiled/v1'
  _PCUSTOMMETRICMESSAGE._serialized_start=29
  _PCUSTOMMETRICMESSAGE._serialized_end=137
  _PCUSTOMMETRIC._serialized_start=140
  _PCUSTOMMETRIC._serialized_end=408
  _PINTCOUNTMETRIC._serialized_start=410
  _PINTCOUNTMETRIC._serialized_end=472
  _PLONGCOUNTMETRIC._serialized_start=474
  _PLONGCOUNTMETRIC._serialized_end=538
  _PINTGAUGEMETRIC._serialized_start=540
  _PINTGAUGEMETRIC._serialized_end=602
  _PLONGGAUGEMETRIC._serialized_start=604
  _PLONGGAUGEMETRIC._serialized_end=668
  _PDOULEGAUGEMETRIC._serialized_start=670
  _PDOULEGAUGEMETRIC._serialized_end=737
  _PINTVALUE._serialized_start=739
  _PINTVALUE._serialized_end=783
  _PLONGVALUE._serialized_start=785
  _PLONGVALUE._serialized_end=830
  _PDOUBLEVALUE._serialized_start=832
  _PDOUBLEVALUE._serialized_end=879
# @@protoc_insertion_point(module_scope)
