# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/Service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from v1 import Span_pb2 as v1_dot_Span__pb2
from v1 import Stat_pb2 as v1_dot_Stat__pb2
from v1 import Cmd_pb2 as v1_dot_Cmd__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10v1/Service.proto\x12\x02v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\rv1/Span.proto\x1a\rv1/Stat.proto\x1a\x0cv1/Cmd.proto2@\n\x04Span\x12\x38\n\x08SendSpan\x12\x10.v1.PSpanMessage\x1a\x16.google.protobuf.Empty\"\x00(\x01\x32\x65\n\x05\x41gent\x12\x31\n\x10RequestAgentInfo\x12\x0e.v1.PAgentInfo\x1a\x0b.v1.PResult\"\x00\x12)\n\x0bPingSession\x12\t.v1.PPing\x1a\t.v1.PPing\"\x00(\x01\x30\x01\x32\xb5\x01\n\x08Metadata\x12\x35\n\x12RequestSqlMetaData\x12\x10.v1.PSqlMetaData\x1a\x0b.v1.PResult\"\x00\x12\x35\n\x12RequestApiMetaData\x12\x10.v1.PApiMetaData\x1a\x0b.v1.PResult\"\x00\x12;\n\x15RequestStringMetaData\x12\x13.v1.PStringMetaData\x1a\x0b.v1.PResult\"\x00\x32\x45\n\x04Stat\x12=\n\rSendAgentStat\x12\x10.v1.PStatMessage\x1a\x16.google.protobuf.Empty\"\x00(\x01\x32\xd8\x03\n\x16ProfilerCommandService\x12:\n\rHandleCommand\x12\x0f.v1.PCmdMessage\x1a\x0f.v1.PCmdRequest\"\x03\x88\x02\x01(\x01\x30\x01\x12\x39\n\x0fHandleCommandV2\x12\x0f.v1.PCmdMessage\x1a\x0f.v1.PCmdRequest\"\x00(\x01\x30\x01\x12=\n\x0b\x43ommandEcho\x12\x14.v1.PCmdEchoResponse\x1a\x16.google.protobuf.Empty\"\x00\x12Z\n\x1e\x43ommandStreamActiveThreadCount\x12\x1c.v1.PCmdActiveThreadCountRes\x1a\x16.google.protobuf.Empty\"\x00(\x01\x12P\n\x17\x43ommandActiveThreadDump\x12\x1b.v1.PCmdActiveThreadDumpRes\x1a\x16.google.protobuf.Empty\"\x00\x12Z\n\x1c\x43ommandActiveThreadLightDump\x12 .v1.PCmdActiveThreadLightDumpRes\x1a\x16.google.protobuf.Empty\"\x00\x42\x85\x01\n!com.navercorp.pinpoint.grpc.traceB\x0cServiceProtoP\x01ZPgitlab.jiagouyun.com/cloudcare-tools/datakit/plugins/inputs/pinpoint/compiled/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.Service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n!com.navercorp.pinpoint.grpc.traceB\014ServiceProtoP\001ZPgitlab.jiagouyun.com/cloudcare-tools/datakit/plugins/inputs/pinpoint/compiled/v1'
  _PROFILERCOMMANDSERVICE.methods_by_name['HandleCommand']._options = None
  _PROFILERCOMMANDSERVICE.methods_by_name['HandleCommand']._serialized_options = b'\210\002\001'
  _SPAN._serialized_start=97
  _SPAN._serialized_end=161
  _AGENT._serialized_start=163
  _AGENT._serialized_end=264
  _METADATA._serialized_start=267
  _METADATA._serialized_end=448
  _STAT._serialized_start=450
  _STAT._serialized_end=519
  _PROFILERCOMMANDSERVICE._serialized_start=522
  _PROFILERCOMMANDSERVICE._serialized_end=994
# @@protoc_insertion_point(module_scope)
